#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
image: Visual Studio 2017
install:
    - git clone https://github.com/johlju/DscResource.Tests
    - ps: Push-Location
    - ps: cd "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests"
    - git checkout ordered-tests
    - ps: Pop-Location
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        # Workaround for issue #774
        $rootTempPath = Join-Path -Path $env:TEMP -ChildPath 'SqlModuleTemp'
        Write-Verbose -Message ('WORKAROUND FOR ISSUE #774: Copying the SQLPS module to a temporary location (''{0}'') for later use by integration tests.' -f $rootTempPath) -Verbose
        New-Item -Path $rootTempPath -Type Directory | Out-Null
        Copy-Item -Path 'C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\*' -Destination $rootTempPath -Recurse -Force

        # Workaround for issue #239
        Write-Verbose -Message 'WORKAROUND FOR ISSUE #239: Removing all SQL related PowerShell modules so they can not be used by the common tests.' -Verbose
        Write-Verbose -Message 'Modules that are being removed:' -Verbose
        Get-Module -ListAvailable -Name 'sql*' | ForEach-Object -Process { Write-Verbose $_.Path -Verbose; Remove-Item $_.Path -Force; }

        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @() -RunTestInOrder

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
