trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - CHANGELOG.md
  tags:
    include:
    - "v*"
    exclude:
    - "*-*"

stages:
  - stage: Build
    jobs:
      - job: Package_Module
        displayName: 'Package Module'
        pool:
          vmImage: 'ubuntu 16.04'
        steps:
          - task: GitVersion@5
            name: gitVersion
            displayName: 'Evaluate Next Version'
            inputs:
              runtime: 'core'
              configFilePath: 'GitVersion.yml'
          - task: PowerShell@2
            name: package
            displayName: 'Build & Package Module'
            inputs:
              filePath: './build.ps1'
              arguments: '-ResolveDependency -tasks pack'
              pwsh: true
            env:
              ModuleVersion: $(gitVersion.InformationalVersion)
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifact'
            inputs:
              pathToPublish: 'output/'
              artifactName: 'output'
              publishLocation: 'Container'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Output "Post-build disk space"
                Get-PSDrive -PSProvider FileSystem

  - stage: Test
    dependsOn: Build
    jobs:
      - job: Test_HQRM
        displayName: 'HQRM'
        pool:
          vmImage: 'vs2017-win2016'
        timeoutInMinutes: 0
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'output'
              downloadPath: '$(Build.SourcesDirectory)'
          - task: PowerShell@2
            name: test
            displayName: 'Run HQRM Test'
            inputs:
              filePath: './build.ps1'
              arguments: '-Tasks hqrmtest'
              pwsh: false
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'output/testResults/NUnit*.xml'
              testRunTitle: 'HQRM'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Output "Post-Test_HQRM disk space"
                Get-PSDrive -PSProvider FileSystem

      - job: Test_Unit
        displayName: 'Unit'
        pool:
          vmImage: 'vs2017-win2016'
        timeoutInMinutes: 0
        steps:
          - powershell: |
              $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
              echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
              echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
            name: dscBuildVariable
            displayName: 'Set Environment Variables'
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'output'
              downloadPath: '$(Build.SourcesDirectory)'
          - task: PowerShell@2
            name: test
            displayName: 'Run Unit Test'
            inputs:
              filePath: './build.ps1'
              arguments: "-Tasks test -PesterScript 'tests/Unit'"
              pwsh: false
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'output/testResults/NUnit*.xml'
              testRunTitle: 'Unit (Windows Server Core)'
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage'
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: 'JaCoCo'
              summaryFileLocation: 'output/testResults/CodeCov*.xml'
              pathToSources: '$(Build.SourcesDirectory)/output/$(dscBuildVariable.RepositoryName)'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Output "Post-Test_Unit disk space"
                Get-PSDrive -PSProvider FileSystem

      - job: Test_Integration_SQL2016
        displayName: 'Integration (SQL2016)'
        pool:
          vmImage: 'windows-2019'
        timeoutInMinutes: 0
        variables:
          # This sets environment variable $env:CI.
          CI: true
          # This sets environment variable $env:CONFIGURATION.
          configuration: Integration_SQL2016
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'output'
              downloadPath: '$(Build.SourcesDirectory)'
          - task: PowerShell@2
            name: configureWinRM
            displayName: 'Configure WinRM'
            inputs:
              targetType: 'inline'
              script: 'winrm quickconfig -quiet'
              pwsh: false
          - powershell: |
              ./build.ps1 -Tasks test -CodeCoverageThreshold 0 -PesterScript @(
                  # Run the integration tests in a specific group order.
                  # Group 1
                  write-output "Pre-MSFT_SqlSetup disk space"
                  get-psdrive -psprovider filesystem
                  'tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1'
                  write-output "Post-MSFT_SqlSetup disk space"
                  get-psdrive -psprovider filesystem
                  # Group 2
                  'tests/Integration/MSFT_SqlAgentAlert.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerNetwork.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerEndPoint.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerDatabaseMail.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlRSSetup.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlDatabaseDefaultLocation.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlDatabase.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlAgentOperator.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlAgentFailsafe.Integration.Tests.ps1'
                  # Group 3
                  'tests/Integration/MSFT_SqlServerRole.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlRS.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlDatabaseUser.Integration.Tests.ps1'
                  # Group 4
                  'tests/Integration/MSFT_SqlScript.Integration.Tests.ps1'
                  # Group 5
                  'tests/Integration/MSFT_SqlServerSecureConnection.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlScriptQuery.Integration.Tests.ps1'
              )
            name: test
            displayName: 'Run Integration Test'
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'output/testResults/NUnit*.xml'
              testRunTitle: 'Integration (SQL Server 2016 / Windows Server 2019)'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Output "Post-Test_Integration_SQL2016 disk space"
                Get-PSDrive -PSProvider FileSystem
            condition: always()

      - job: Test_Integration_SQL2017
        displayName: 'Integration (SQL2017)'
        pool:
          vmImage: 'windows-2019'
        timeoutInMinutes: 0
        variables:
          # This sets environment variable $env:CI.
          CI: true
          # This sets environment variable $env:CONFIGURATION.
          configuration: Integration_SQL2017
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'output'
              downloadPath: '$(Build.SourcesDirectory)'
          - task: PowerShell@2
            name: configureWinRM
            displayName: 'Configure WinRM'
            inputs:
              targetType: 'inline'
              script: 'winrm quickconfig -quiet'
              pwsh: false
          - powershell: |
              ./build.ps1 -Tasks test -CodeCoverageThreshold 0 -PesterScript @(
                  # Run the integration tests in a specific group order.
                  # Group 1
                  'tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1'
                  # Group 2
                  'tests/Integration/MSFT_SqlAgentAlert.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerNetwork.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerEndPoint.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServerDatabaseMail.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlRSSetup.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlDatabaseDefaultLocation.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlDatabase.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlAgentOperator.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlAgentFailsafe.Integration.Tests.ps1'
                  # Group 3
                  'tests/Integration/MSFT_SqlServerRole.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlRS.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlDatabaseUser.Integration.Tests.ps1'
                  # Group 4
                  'tests/Integration/MSFT_SqlScript.Integration.Tests.ps1'
                  # Group 5
                  'tests/Integration/MSFT_SqlServerSecureConnection.Integration.Tests.ps1'
                  'tests/Integration/MSFT_SqlScriptQuery.Integration.Tests.ps1'
              )
            name: test
            displayName: 'Run Integration Test'
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'output/testResults/NUnit*.xml'
              testRunTitle: 'Integration (SQL Server 2017 / Windows Server 2019)'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Output "Post-Test_Integration_SQL2017 disk space"
                Get-PSDrive -PSProvider FileSystem

  - stage: Deploy
    dependsOn: Test
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        ),
        contains(variables['System.TeamFoundationCollectionUri'], 'dsccommunity')
      )
    jobs:
      - job: Deploy_Module
        displayName: 'Deploy Module'
        pool:
          vmImage: 'ubuntu 16.04'
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'output'
              downloadPath: '$(Build.SourcesDirectory)'
          - task: PowerShell@2
            name: publishRelease
            displayName: 'Publish Release'
            inputs:
              filePath: './build.ps1'
              arguments: '-tasks publish'
              pwsh: true
            env:
              GitHubToken: $(GitHubToken)
              GalleryApiToken: $(GalleryApiToken)
          - task: PowerShell@2
            name: sendChangelogPR
            displayName: 'Send Changelog PR'
            inputs:
              filePath: './build.ps1'
              arguments: '-tasks Create_ChangeLog_GitHub_PR'
              pwsh: true
            env:
              GitHubToken: $(GitHubToken)
