---
####################################################
#          ModuleBuilder Configuration             #
####################################################
CopyDirectories:
  - DSCResources
  - en-US
  - Modules
Encoding: UTF8
VersionedOutputDirectory: true

####################################################
#           Pipeline Configuration                 #
####################################################
BuildWorkflow:
  '.':
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  pack:
    - build
    - package_module_nupkg

  hqrmtest:
    - DscResource_Tests_Stop_On_Fail

  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  publish:
    - Publish_release_to_GitHub
    - publish_module_to_gallery


####################################################
#       PESTER  Configuration                      #
####################################################

Pester:
  OutputFormat: NUnitXML
  ExcludeFromCodeCoverage:
  Script:
    # Run the script in order. First all of unit tests in no particular order,
    # and then all the integration tests in a specific group order.
    - tests/Unit
    # Group 1
    - tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1
    # Group 2
    - tests/Integration/MSFT_SqlAgentAlert.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlServerNetwork.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlServerEndPoint.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlServerDatabaseMail.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlRSSetup.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlDatabaseDefaultLocation.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlDatabase.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlAgentOperator.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlAgentFailsafe.Integration.Tests.ps1
    # Group 3
    - tests/Integration/MSFT_SqlServerRole.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlRS.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlDatabaseUser.Integration.Tests.ps1
    # Group 4
    - tests/Integration/MSFT_SqlScript.Integration.Tests.ps1
    # Group 5
    - tests/Integration/MSFT_SqlServerSecureConnection.Integration.Tests.ps1
    - tests/Integration/MSFT_SqlScriptQuery.Integration.Tests.ps1
  ExcludeTag:
  Tag:
  CodeCoverageThreshold: 85

DscTest:
  ExcludeTag:
    - "Common Tests - New Error-Level Script Analyzer Rules"
  Tag:
  ExcludeSourceFile:
    - output
  ExcludeModuleFile:

Resolve-Dependency:
  Gallery: 'PSGallery'
  AllowPrerelease: false
  Verbose: false

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: dscbot
  GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false
