[ClassVersion("1.0.0.0"), FriendlyName("SqlSetup")]
class MSFT_SqlSetup : OMI_BaseResource
{
    [Write, Description("The action to be performed. Default value is 'Install'."), ValueMap{"Install","InstallFailoverCluster","AddNode","PrepareFailoverCluster","CompleteFailoverCluster"}, Values{"Install","InstallFailoverCluster","AddNode","PrepareFailoverCluster","CompleteFailoverCluster"}] String Action;
    [Key, Description("Name of the SQL instance to be installed.")] String InstanceName;
};
